import React from "react"
import { Poppins } from "next/font/google"

import StyledComponentsRegistry from "../lib/AntdRegistry"
import Navbar from "@/app/components/navbar/Navbar"
import MyCustomProvider from '../app/redux/MyCustomProvider';
// import "@/globals.css"
import '@/app/globals.css'
import Footer from "./components/footer/Footer"

const poppins = Poppins({ weight:"400", subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/favicon/favicon.ico',
        href: '/favicon/favicon.ico',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/favicon/favicon.ico',
        href: '/favicon/favicon.ico',
      },
    ],
  }
}

const RootLayout = ({ children }) => (
  <html lang="en">

    <body className={poppins.className}>
    <MyCustomProvider>
      <StyledComponentsRegistry>
        
 <Navbar/>

        {children}
 <Footer/>
        </StyledComponentsRegistry>
        </MyCustomProvider>
    </body>
  </html>
)

export default RootLayout
